### ISSUE TITLE
https://github.com/brissettdwayne/Memory

### ISSUE THREAD

**Issue by brissettdwayne** [brissettdwayne/Memory#1]
I need some help getting started for making my game actually work. I can't figure out how to check if one card is equal to another. For example, I want to check if #flip-one has the same class of all of the other divs. I tried using a for loop but that wasn't working at all.

**Comment by ajhofferber** [comment]
Hey Dwayne,

So there are a few different ways that you could go about checking to see if you have a pair. Depending on the way that your cards store their values. When you say you "want to check if #flip-one has the same class of all of the other divs", what do you mean by "all of the other divs"?
